
# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch:

name: app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
      
    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: 'npm install, build, and test'
      run: |
        cd app
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Azure webapp deploy'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.WEBAPP }}
        package:  ${{ github.workspace }}/app
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az extension add -n application-insights
          locName=`az group show --name ${{ secrets.RG }} --query location --output tsv`
          az monitor app-insights component create --app apimon${{ secrets.WEBAPP }} --location $locName --kind web -g ${{ secrets.RG }} --application-type web --retention-time 30
          instrumentationKey=`az monitor app-insights component show --app apimon${{ secrets.WEBAPP }} --resource-group ${{ secrets.RG }} --query  "instrumentationKey" --output tsv`
          az webapp config appsettings set --name ${{ secrets.WEBAPP }} --resource-group ${{ secrets.RG }} --settings APPINSIGHTS_INSTRUMENTATIONKEY=$instrumentationKey APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=$instrumentationKey ApplicationInsightsAgent_EXTENSION_VERSION=~2
